#!/usr/bin/env bash
# Shell Script that bans any IP on the 192.168.1.0 /24 subnet
# 192.168.1.1 is reserved
#IP not banned .20 .21 .22

i=2

while [$i -le 253]
do
  if [$i -ne 20 -a $i -ne 21 -a $i -ne 22]; then
    echo "BANNED: arp -s 192.168.1.$i"
    arp -s 192.168.1.$i 00:00:00:00:00:0a
  else
    echo "IP NOT BANNED: 192.168.1.$1************"
    echo "***************************************"
  fi
  
  i = 'expr $i +1'
done
